[package]
name = "pxsol-spl"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2"
spl-associated-token-account = { version="5", features = [ "no-entrypoint" ] }
spl-token-2022 = {version = "5", features = [ "no-entrypoint" ] }
